-y added

diff --git a/rabbitmq/tasks/main.yml b/rabbitmq/tasks/main.yml
--- a/rabbitmq/tasks/main.yml
+++ b/rabbitmq/tasks/main.yml
@@ -1,3 +1,68 @@
-- name: Rabbitmq
-  ansible.builtin.debug:
-    msg: Rabbitmq
+#source common.sh
+#
+#roboshop_app_password=$1
+#if [ -z "${roboshop_app_password}" ]; then
+#echo -e "\e[31mRabbitMQ App User password is missing\e[0m"
+#exit 1
+#fi
+#print_head "setup Earlang Repo"
+#curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh |  bash &>>"${log_file}"
+#status_check $?
+#print_head "set up Rabbitmq Repo"
+#curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash &>>"${log_file}"
+#status_check $?
+#print_head "install Rabbit and Earlang"
+#yum install rabbitmq-server erlang -y &>>"${log_file}"
+#status_check $?
+#
+#print_head "Enable Rabbitmq Service"
+#systemctl enable rabbitmq-server &>>"${log_file}"
+#status_check $?
+#print_head "Start Rabbitmq service"
+#systemctl start rabbitmq-server &>>"${log_file}"
+#status_check $?
+#print_head "Add Application User"
+#rabbitmqctl list_users | grep roboshop &>>"${log_file}"
+#if [ $? -ne 0 ]; then
+#rabbitmqctl add_user roboshop ${roboshop_app_password} &>>"${log_file}"
+#fi
+#status_check $?
+#
+#print_head "Configure permissions for app user"
+#rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" &>>"${log_file}"
+#status_check $?
+
+- name: setup Earlang Repo
+  ansible.builtin.yum:
+    name: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
+    state: installed
+
+- name: set up Rabbitmq Repo
+  ansible.builtin.yum:
+    name: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh
+    state: installed
+
+- name: install Rabbit and Earlang
+  ansible.builtin.yum:
+    name:
+      - rabbitmq-server
+      - erlang
+    state: installed
+
+- name: Start Rabbitmq Service
+  ansible.builtin.systemd:
+    name: rabbitmq-server
+    state: restarted
+    enabled: true
+
+- name: |-
+    Add user to server and assign full access control on / vhost.
+    The user might have permission rules for other vhost but you don't care.
+  community.rabbitmq.rabbitmq_user:
+    user: roboshop
+    password: roboshop123
+    vhost: /
+    configure_priv: .*
+    read_priv: .*
+    write_priv: .*
+    state: present
